language: go

os:
  - linux
  - osx

dist: trusty

go:
  - 1.8rc3

addons: { apt: { packages: [ "pkg-config", "libpcre++0", "libpcre++-dev" ] } }

install:
- go get github.com/Masterminds/glide
- glide up --strip-vendor

script: make test
