---
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: cart
    name: cart
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: cart
    template:
      metadata:
        labels:
          name: cart
      spec:
        containers:
        - image: weaveworksdemos/cart:0.4.0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: cart
          ports:
          - containerPort: 80
            name: cart
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: cart
    name: cart
    namespace: sockshop
  spec:
    ports:
    - name: cart
      port: 80
      targetPort: cart
    selector:
      name: cart
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: catalogue-db
    name: catalogue-db
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: catalogue-db
    template:
      metadata:
        labels:
          name: catalogue-db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: socksdb
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          image: weaveworksdemos/catalogue-db:0.3.0
          livenessProbe:
            httpGet:
              path: /health
              port: 3306
            initialDelaySeconds: 300
            periodSeconds: 3
          name: catalogue-db
          ports:
          - containerPort: 3306
            name: catalogue-db
          readinessProbe:
            httpGet:
              path: /health
              port: 3306
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: catalogue-db
    name: catalogue-db
    namespace: sockshop
  spec:
    ports:
    - name: catalogue-db
      port: 3306
      targetPort: catalogue-db
    selector:
      name: catalogue-db
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: catalogue
    name: catalogue
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: catalogue
    template:
      metadata:
        labels:
          name: catalogue
      spec:
        containers:
        - env:
          - name: ZIPKIN
            value: http://zipkin:9411/api/v1/spans
          image: weaveworksdemos/catalogue:0.3.0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: catalogue
          ports:
          - containerPort: 80
            name: catalogue
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: catalogue
    name: catalogue
    namespace: sockshop
  spec:
    ports:
    - name: catalogue
      port: 80
      targetPort: catalogue
    selector:
      name: catalogue
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: front-end
    name: front-end
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: front-end
    template:
      metadata:
        labels:
          name: front-end
      spec:
        containers:
        - image: weaveworksdemos/front-end:0.3.0
          livenessProbe:
            httpGet:
              path: /health
              port: 8079
            initialDelaySeconds: 300
            periodSeconds: 3
          name: front-end
          ports:
          - containerPort: 8079
            name: front-end
          readinessProbe:
            httpGet:
              path: /health
              port: 8079
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: front-end
    name: front-end
    namespace: sockshop
  spec:
    ports:
    - name: front-end
      port: 8079
      targetPort: front-end
    selector:
      name: front-end
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: orders
    name: orders
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: orders
    template:
      metadata:
        labels:
          name: orders
      spec:
        containers:
        - image: weaveworksdemos/orders:0.4.2
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: orders
          ports:
          - containerPort: 80
            name: orders
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: orders
    name: orders
    namespace: sockshop
  spec:
    ports:
    - name: orders
      port: 80
      targetPort: orders
    selector:
      name: orders
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: payment
    name: payment
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: payment
    template:
      metadata:
        labels:
          name: payment
      spec:
        containers:
        - env:
          - name: ZIPKIN
            value: http://zipkin:9411/api/v1/spans
          image: weaveworksdemos/payment:0.4.0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: payment
          ports:
          - containerPort: 80
            name: payment
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: payment
    name: payment
    namespace: sockshop
  spec:
    ports:
    - name: payment
      port: 80
      targetPort: payment
    selector:
      name: payment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: queue-master
    name: queue-master
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: queue-master
    template:
      metadata:
        labels:
          name: queue-master
      spec:
        containers:
        - image: weaveworksdemos/queue-master:0.3.0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: queue-master
          ports:
          - containerPort: 80
            name: queue-master
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: queue-master
    name: queue-master
    namespace: sockshop
  spec:
    ports:
    - name: queue-master
      port: 80
      targetPort: queue-master
    selector:
      name: queue-master
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: rabbitmq
    name: rabbitmq
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: rabbitmq
    template:
      metadata:
        labels:
          name: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3
          livenessProbe:
            httpGet:
              path: /health
              port: 5672
            initialDelaySeconds: 300
            periodSeconds: 3
          name: rabbitmq
          ports:
          - containerPort: 5672
            name: rabbitmq
          readinessProbe:
            httpGet:
              path: /health
              port: 5672
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: rabbitmq
    name: rabbitmq
    namespace: sockshop
  spec:
    ports:
    - name: rabbitmq
      port: 5672
      targetPort: rabbitmq
    selector:
      name: rabbitmq
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: shipping
    name: shipping
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: shipping
    template:
      metadata:
        labels:
          name: shipping
      spec:
        containers:
        - image: weaveworksdemos/shipping:0.4.0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: shipping
          ports:
          - containerPort: 80
            name: shipping
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: shipping
    name: shipping
    namespace: sockshop
  spec:
    ports:
    - name: shipping
      port: 80
      targetPort: shipping
    selector:
      name: shipping
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: user
    name: user
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: user
    template:
      metadata:
        labels:
          name: user
      spec:
        containers:
        - env:
          - name: MONGO_HOST
            value: user-db:27017
          - name: ZIPKIN
            value: http://zipkin:9411/api/v1/spans
          image: weaveworksdemos/user:0.4.0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: user
          ports:
          - containerPort: 80
            name: user
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: user
    name: user
    namespace: sockshop
  spec:
    ports:
    - name: user
      port: 80
      targetPort: user
    selector:
      name: user
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: zipkin
    name: zipkin
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: zipkin
    template:
      metadata:
        labels:
          name: zipkin
      spec:
        containers:
        - image: openzipkin/zipkin
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 300
            periodSeconds: 3
          name: zipkin
          ports:
          - containerPort: 9411
            name: zipkin
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: zipkin
    name: zipkin
    namespace: sockshop
  spec:
    ports:
    - name: zipkin
      port: 9411
      targetPort: zipkin
    selector:
      name: zipkin
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: cart-db
    name: cart-db
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: cart-db
    template:
      metadata:
        labels:
          name: cart-db
      spec:
        containers:
        - livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 3
          name: cart-db
          ports:
          - containerPort: 80
            name: cart-db
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: cart-db
    name: cart-db
    namespace: sockshop
  spec:
    ports:
    - name: cart-db
      port: 80
      targetPort: cart-db
    selector:
      name: cart-db
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: orders-db
    name: orders-db
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: orders-db
    template:
      metadata:
        labels:
          name: orders-db
      spec:
        containers:
        - env:
          - name: ZIPKIN
            value: http://zipkin:9411/api/v1/spans
          image: mongo
          name: orders-db
          ports:
          - containerPort: 27017
            name: orders-db
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: orders-db
    name: orders-db
    namespace: sockshop
  spec:
    ports:
    - name: orders-db
      port: 27017
      targetPort: orders-db
    selector:
      name: orders-db
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: user-db
    name: user-db
    namespace: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: user-db
    template:
      metadata:
        labels:
          name: user-db
      spec:
        containers:
        - env:
          - name: ZIPKIN
            value: http://zipkin:9411/api/v1/spans
          image: weaveworksdemos/user-db:0.3.0
          name: user-db
          ports:
          - containerPort: 27017
            name: user-db
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: user-db
    name: user-db
    namespace: sockshop
  spec:
    ports:
    - name: user-db
      port: 27017
      targetPort: user-db
    selector:
      name: user-db
kind: List

